### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by pedromxavier** [cjdoris/MicroMamba.jl#13]
`libmamba` raises a critical error when using
- `julia v1.9.0`
- `PythonCall v0.9.13`
- `CondaPkg v0.2.18`
- `MicroMamba v0.1.12`
- `micromamba_jll v1.4.3`
to build [PySA.jl](https://github.com/psrenergy/PySA.jl) on Windows, as seen in:
https://github.com/psrenergy/PySA.jl/actions/runs/5035976115/jobs/9031837746

Restricting to `micromamba_jll<1.4.3` seems to fix the problem:
https://github.com/psrenergy/PySA.jl/actions/runs/5037994714/jobs/9035182222

**Comment by cjdoris** [comment]
Thanks this is fixed now - you can't install the broken versions of micromamba in MicroMamba.jl now.
