### ISSUE TITLE
latest micromamba installs micromamba_jll v1.4.1+0 while pinning with previous version upgrades micromamba_jll to v1.4.3+0

### ISSUE THREAD

**Issue by ppalmes** [cjdoris/MicroMamba.jl#14]
latest micromamba pulls micromamba_jll v1.4.1+0 instead of v1.4.3+0

**Comment by ppalmes** [comment]
yeah but the solution breaks [CondaPkg](https://github.com/cjdoris/CondaPkg.jl/issues/93#issue-1733096850) in M1.

**Comment by ppalmes** [comment]
do we have any solution? i have to bound my AutoMLPipeline.jl package to Micromamba v0.1.12 because the CondaPkg breaks with micromamba_jll v1.4.2 with Micromamba v0.1.13 in Mac M1.

**Comment by cjdoris** [comment]
This should be fixed now - upgrade to MicroMamba v0.1.14 and you should be able to get newer versions of micromamba.
