### ISSUE TITLE
Use artifacts

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/MicroMamba.jl#2]
Use artifacts to install MicroMamba

**Comment by fonsp** [comment]
This would be fantastic! It means that people can use the package even when they do not have access to `http://mamba.pm`, which includes:
- Some schools, universities, companies
- Countries with restrictive internet access (notably China)
- People with bad/no internet access, who still use Julia through a USB key.
- Maybe us in the future! If mamba.pm goes offline, we still want our old projects to work.

And I am sure that there are other advantages!

**Comment by cjdoris** [comment]
OK this is now implemented on the main branch. I'm about to make a release.
