### ISSUE TITLE
"ERROR: LoadError: InitError: Unable to automatically install 'micromamba-0.22.0'" in Github CI Actions

### ISSUE THREAD

**Issue by CarloLucibello** [cjdoris/MicroMamba.jl#8]
See https://github.com/CarloLucibello/HuggingFaceDatasets.jl/issues/1

**Comment by Roger-luo** [comment]
same here in https://github.com/QuEraComputing/Bloqade.jl/runs/6445238329?check_suite_focus=true#step:5:308

anyone might know why this happens? seems to be a Julia artifact issue?

**Comment by Roger-luo** [comment]
This error magically disappeared today! I don't know what happens but I guess it can be closed then.
